server/src/oscarbluelight/dashboard/offers/models.py
from oscar.apps.dashboard.offers.models import *  # noqa

server/src/oscarbluelight/offer/models.py
from django.conf import settings
from django.core import exceptions
from django.core.cache import caches
from django.db import models, IntegrityError
from django.db.models import F
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import force_str
from django_redis import get_redis_connection
from oscar.models.fields import AutoSlugField
from oscar.apps.offer.abstract_models import (
    AbstractBenefit,
    AbstractCondition,
    AbstractConditionalOffer,
    AbstractRange,
    AbstractRangeProduct,
    AbstractRangeProductFileUpload
)
from oscar.apps.offer.results import (
    SHIPPING_DISCOUNT,
    ZERO_DISCOUNT,
    BasketDiscount,
    PostOrderAction,
    ShippingDiscount
)
from oscar.apps.offer.utils import load_proxy
import copy
import logging
import random

logger = logging.getLogger(__name__)

cache = caches[settings.REDIS_CACHE_ALIAS]


def _init_proxy_class(obj, Klass):
    # Check if we're already the correct class
    if obj.__class__ == Klass:
        return obj

    # Check if we're using multi-table inheritance
    model_name = Klass._meta.model_name
    if hasattr(obj, model_name):
        return getattr(obj, model_name)

    # Else, it's just a proxy model
    proxy = copy.deepcopy(obj)
    proxy.__class__ = Klass
    return proxy


class OfferGroup(models.Model):
    """
    Ordered group of Offers
    """
    name = models.CharField(max_length=64, null=False)
    slug = AutoSlugField(populate_from='name', unique=True, null=True, default=None)
    priority = models.IntegerField(null=False, unique=True)
    is_system_group = models.BooleanField(default=False, editable=False)

    class Meta:
        verbose_name = _('OfferGroup')
        ordering = ('-priority', )

    def __str__(self):
        return '{} (priority {})'.format(self.name, self.priority)


class ConditionalOffer(AbstractConditionalOffer):
    """
    groups  -- user groups
    offer_group -- FK to OfferGroup
    offerGroupA => [ o1, v2, o3 ], priority 1
    offerGroupB => [ o4, v3 ], priority 2
    To consume offers, loop through offers in offer group based on priority
    to consume OfferGroup -> only move to next (greater priority val) when previous
    offerGroup is consumed
    """
    short_name = models.CharField(_("Short Name"),
        max_length=50,
        help_text=_("Abbreviated version of offer name"))
    desktop_image = models.ImageField(_("Ad Image (Desktop)"),
        null=True,
        blank=True,
        upload_to=getattr(settings, 'BLUELIGHT_OFFER_IMAGE_FOLDER'),
        help_text=_("Desktop image used for promo display."))
    mobile_image = models.ImageField(_("Ad Image (Mobile)"),
        null=True,
        blank=True,
        upload_to=getattr(settings, 'BLUELIGHT_OFFER_IMAGE_FOLDER'),
        help_text=_("Mobile image used for promo display."))
    # When offer_type == "User", we use groups to determine which users get the offer
    groups = models.ManyToManyField('auth.Group',
        verbose_name=_("User Groups"),
        blank=True,
        help_text=_("Select which User Groups are eligible for this offer. If none are selected, all "
                    "users are eligible."))
    offer_group = models.ForeignKey(OfferGroup,
        verbose_name=_("Offer Group"),
        related_name='offers',
        null=True,
        on_delete=models.CASCADE,
        help_text=_("Select the Offer Group that this offer belongs to. Offer Group controls the order "
                    "offers are applied in and which offers may be combined together."))

    class Meta:
        ordering = ('-offer_group__priority', '-priority', 'pk')

    def availability_restrictions(self):
        restrictions = super().availability_restrictions()
        if self.offer_type == self.USER:
            restrictions.append({
                'description': _("Offer is limited to user groups: %s") % ', '.join(g.name for g in self.groups.all()),
                'is_satisfied': True,
            })
        return restrictions

    def apply_benefit(self, basket):
        try:
            return super().apply_benefit(basket)
        except Exception as e:
            logger.exception(e)
            return ZERO_DISCOUNT

    def record_usage(self, discount):
        ConditionalOffer.objects\
                        .filter(pk=self.pk)\
                        .update(num_applications=(F('num_applications') + discount['freq']),
                                total_discount=(F('total_discount') + discount['discount']),
                                num_orders=(F('num_orders') + 1))
    record_usage.alters_data = True


class Benefit(AbstractBenefit):
    def proxy(self):
        if self.proxy_class:
            Klass = load_proxy(self.proxy_class)
            return _init_proxy_class(self, Klass)
        return super().proxy()

    @property
    def name(self):
        return force_str(super().name)

    @property
    def type_name(self):
        benefit_classes = getattr(settings, 'BLUELIGHT_BENEFIT_CLASSES', [])
        names = dict(benefit_classes)
        names['oscarbluelight.offer.benefits.CompoundBenefit'] = _("Compound benefit")
        return names.get(self.proxy_class, self.proxy_class)

    @property
    def non_voucher_offers(self):
        return self.offers.exclude(offer_type=ConditionalOffer.VOUCHER).all()

    @property
    def vouchers(self):
        vouchers = []
        for offer in self.offers.filter(offer_type=ConditionalOffer.VOUCHER).all():
            for voucher in offer.vouchers.filter(parent=None).all():
                vouchers.append(voucher)
        return vouchers

    def clean(self):
        if self.type:
            raise exceptions.ValidationError(_("Benefit should not have a type field. Use proxy class instead."))
        proxy_instance = self.proxy()
        cleaner = getattr(proxy_instance, '_clean', None)
        if cleaner and callable(cleaner):
            return cleaner()
        return super().clean()

    def save(self, *args, **kwargs):
        ret = super().save(*args, **kwargs)
        # If the elected proxy_class isn't a proxy model, it has it's own table where a row needs to exist.
        if self.proxy_class:
            Klass = load_proxy(self.proxy_class)
            if self.__class__ != Klass and not Klass._meta.proxy and not Klass.objects.filter(pk=self.pk).exists():
                proxy = copy.deepcopy(self)
                proxy.__class__ = Klass
                proxy.save()
        return ret


class Condition(AbstractCondition):
    def proxy(self):
        if self.proxy_class:
            Klass = load_proxy(self.proxy_class)
            return _init_proxy_class(self, Klass)
        return super().proxy()

    @property
    def name(self):
        return force_str(super().name)

    @property
    def type_name(self):
        condition_classes = getattr(settings, 'BLUELIGHT_CONDITION_CLASSES', [])
        names = dict(condition_classes)
        names['oscarbluelight.offer.conditions.CompoundCondition'] = _("Compound condition")
        return names.get(self.proxy_class, self.proxy_class)

    @property
    def non_voucher_offers(self):
        return self.offers.exclude(offer_type=ConditionalOffer.VOUCHER).all()

    @property
    def vouchers(self):
        vouchers = []
        for offer in self.offers.filter(offer_type=ConditionalOffer.VOUCHER).all():
            for voucher in offer.vouchers.filter(parent=None).all():
                vouchers.append(voucher)
        return vouchers

    def clean(self):
        if self.type:
            raise exceptions.ValidationError(_("Condition should not have a type field. Use proxy class instead."))
        proxy_instance = self.proxy()
        cleaner = getattr(proxy_instance, '_clean', None)
        if cleaner and callable(cleaner):
            return cleaner()

    def save(self, *args, **kwargs):
        ret = super().save(*args, **kwargs)
        # If the elected proxy_class isn't a proxy model, it has it's own table where a row needs to exist.
        if self.proxy_class:
            Klass = load_proxy(self.proxy_class)
            if self.__class__ != Klass and not Klass._meta.proxy and not Klass.objects.filter(pk=self.pk).exists():
                proxy_instance = copy.deepcopy(self)
                proxy_instance.__class__ = Klass
                proxy_instance.save(force_insert=True)
        return ret


class Range(AbstractRange):
    cache_version = models.PositiveIntegerField(_("Cache Version"),
        editable=False,
        default=1)

    def delete(self, *args, **kwargs):
        # Disallow deleting a range with any dependents
        if self.benefit_set.exists() or self.condition_set.exists():
            raise IntegrityError(_('Can not delete range with a dependent benefit or condition.'))
        return super().delete(*args, **kwargs)

    @property
    def _cache_ttl(self):
        center = getattr(settings, 'BLUELIGHT_RANGE_CACHE_TTL', 86400 * 7)
        entropy = 86400 / 2
        return random.randrange(
            max(0, center - entropy),
            (center + entropy))

    @property
    def _cache_key(self):
        return cache.make_key('oscarbluelight.models.Range.{}-{}.products'.format(self.pk, self.cache_version))

    _member_cache = None

    def contains_product(self, product):
        # If this range contains everything, short-circuit the normal (slower) logic
        if self.includes_all_products:
            excluded_product_ids = self._excluded_product_ids()
            if product.id in excluded_product_ids:
                return False
            return True
        key = self._cache_key
        conn = get_redis_connection(settings.REDIS_CACHE_ALIAS)
        # Populate redis cache if it doesn't exist, then get the set of included product IDs
        if self._member_cache is None:
            if conn.exists(key):
                self._member_cache = { int(pk) for pk in conn.smembers(key) }
            else:

server/src/oscarbluelight/dashboard/offers/forms.py
from django import forms
from django.db.models import Q
from django.conf import settings
from django.contrib.auth.models import Group
from django.utils.translation import ugettext_lazy as _
from oscar.forms.widgets import DatePickerInput
from oscar.apps.dashboard.offers.forms import (
    MetaDataForm as BaseMetaDataForm,
    RestrictionsForm as BaseRestrictionsForm,
)
from django.forms import ModelMultipleChoiceField
from oscar.core.loading import get_model

ConditionalOffer = get_model('offer', 'ConditionalOffer')
CompoundBenefit = get_model('offer', 'CompoundBenefit')
Benefit = get_model('offer', 'Benefit')
CompoundCondition = get_model('offer', 'CompoundCondition')
Condition = get_model('offer', 'Condition')
Range = get_model('offer', 'Range')
OfferGroup = get_model('offer', 'OfferGroup')
Order = get_model('order', 'Order')
SourceType = get_model('payment', 'SourceType')


class BenefitSearchForm(forms.Form):
    range = forms.ModelChoiceField(required=False, queryset=Range.objects.order_by('name'))


class ConditionSearchForm(forms.Form):
    range = forms.ModelChoiceField(required=False, queryset=Range.objects.order_by('name'))


class OrderDiscountSearchForm(forms.Form):
    number = forms.CharField(required=False, label=_("Order number"))
    status = forms.ChoiceField(required=False, label=_("Order status"), choices=[])
    date_from = forms.DateField(required=False, label=_("Date from"), widget=DatePickerInput)
    date_to = forms.DateField(required=False, label=_("Date to"), widget=DatePickerInput)
    product = forms.CharField(required=False, label=_("Product"))
    payment_method = forms.ChoiceField(required=False, label=_("Payment method"), choices=[])

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['status'].choices = self.get_order_status_choices()
        self.fields['payment_method'].choices = self.get_payment_method_choices()

    def get_order_status_choices(self):
        return [('', '---------')] + [(v, v) for v in Order.all_statuses()]

    def get_payment_method_choices(self):
        return [('', '---------')] + [(src.code, src.name) for src in SourceType.objects.all()]

    def filter_queryset(self, qs):
        if not self.is_valid():
            return qs
        data = self.cleaned_data
        is_filtered = False
        if data.get('number'):
            qs = qs.filter(order__number__icontains=data['number'])
            is_filtered = True
        if data.get('status'):
            qs = qs.filter(order__status=data['status'])
            is_filtered = True
        if data.get('date_from'):
            qs = qs.filter(order__date_placed__gte=data['date_from'])
            is_filtered = True
        if data.get('date_to'):
            qs = qs.filter(order__date_placed__lte=data['date_to'])
            is_filtered = True
        if data.get('product'):
            qs = qs.filter((
                Q(order__lines__title__icontains=data['product']) |  # NOQA
                Q(order__lines__upc__icontains=data['product']) |  # NOQA
                Q(order__lines__partner_sku__icontains=data['product'])
            ))
            is_filtered = True
        if data.get('payment_method'):
            qs = qs.filter(order__sources__source_type__code=data['payment_method'])
            is_filtered = True
        return qs, is_filtered


class BenefitForm(forms.ModelForm):
    _benefit_classes = getattr(settings, 'BLUELIGHT_BENEFIT_CLASSES', [])
    proxy_class = forms.ChoiceField(
        choices=_benefit_classes,
        required=True,
        label=_('Type'),
        help_text=_('Select a benefit type'))

    class Meta:
        model = Benefit
        fields = ['range', 'proxy_class', 'value', 'max_affected_items']


class ConditionForm(forms.ModelForm):
    _condition_classes = getattr(settings, 'BLUELIGHT_CONDITION_CLASSES', [])
    proxy_class = forms.ChoiceField(
        choices=_condition_classes,
        required=True,
        label=_('Type'),
        help_text=_('Select a condition type'))

    class Meta:
        model = Condition
        fields = ['range', 'proxy_class', 'value', ]


class CompoundBenefitForm(forms.ModelForm):
    CPATH = "%s.%s" % (CompoundBenefit.__module__, CompoundBenefit.__name__)
    proxy_class = forms.ChoiceField(
        choices=(
            (CPATH, _('Compound Benefit')),
        ),
        initial=CPATH,
        disabled=True,
        label=_('Type'),
        help_text=_('Select a benefit type'))

    class Meta:
        model = CompoundBenefit
        fields = ['proxy_class', 'subbenefits']


class CompoundConditionForm(forms.ModelForm):
    CPATH = "%s.%s" % (CompoundCondition.__module__, CompoundCondition.__name__)
    proxy_class = forms.ChoiceField(
        choices=(
            (CPATH, _('Compound Condition')),
        ),
        initial=CPATH,
        disabled=True,
        label=_('Type'),
        help_text=_('Select a condition type'))

    class Meta:
        model = CompoundCondition
        fields = ['proxy_class', 'conjunction', 'subconditions']


class MetaDataForm(BaseMetaDataForm):
    offer_group = forms.ModelChoiceField(
        label=_('Offer Group'),
        queryset=OfferGroup.objects.get_queryset(),
        help_text=_('Offer group to which this offer belongs'))

    class Meta(BaseMetaDataForm.Meta):
        fields = ('name', 'short_name', 'description', 'offer_group', 'priority')


class BenefitSelectionForm(forms.ModelForm):
    class Meta:
        model = ConditionalOffer
        fields = ('benefit', )


class ConditionSelectionForm(forms.ModelForm):
    class Meta:
        model = ConditionalOffer
        fields = ('condition', )


class RestrictionsForm(BaseRestrictionsForm):
    limit_by_group = forms.BooleanField(
        label=_("Limit offer to selected user groups"),
        required=False)

    groups = forms.ModelMultipleChoiceField(
        label=_("User Groups"),
        queryset=Group.objects.get_queryset(),
        help_text=_("Which user groups will be able to apply this offer?"),
        required=False)

    class Meta:
        model = ConditionalOffer
        fields = ('start_datetime', 'end_datetime',
                  'limit_by_group', 'groups',
                  'max_basket_applications', 'max_user_applications',
                  'max_global_applications', 'max_discount')

    def clean(self):
        cleaned_data = super().clean()
        cleaned_data['limit_by_group'] = cleaned_data.get('limit_by_group', False)
        if not cleaned_data['limit_by_group']:
            cleaned_data['groups'] = []
        return cleaned_data


class OfferGroupForm(forms.ModelForm):
    offers = ModelMultipleChoiceField(
        queryset=ConditionalOffer.objects.order_by('name').all(),
        widget=forms.widgets.SelectMultiple(),
        required=False
    )

    class Meta:
        model = OfferGroup
        fields = ('name', 'priority', 'offers', )


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance:
            self.initial['offers'] = self.instance.offers.all()


    def save(self, *args, **kwargs):
        offer_group = super().save(*args, **kwargs)
        offer_group.offers.set(self.cleaned_data['offers'])
        return offer_group

server/src/oscarbluelight/dashboard/offers/__init__.py
default_app_config = 'oscarbluelight.dashboard.offers.apps.OffersDashboardConfig'

server/src/oscarbluelight/dashboard/vouchers/__init__.py
default_app_config = 'oscarbluelight.dashboard.vouchers.apps.VouchersDashboardConfig'

server/src/oscarbluelight/offer/__init__.py
default_app_config = 'oscarbluelight.offer.apps.OfferConfig'

from .results import OfferApplications  # NOQA

server/src/oscarbluelight/templates/oscar/dashboard/offers/benefit_delete.html
{% extends 'oscar/dashboard/layout.html' %}
{% load i18n %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block title %}
    {% trans "Delete benefit" %} | {% trans "Benefits" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:benefit-list' %}">{% trans "Benefits" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:benefit-update' pk=object.pk %}">'{{ object.name }}'</a>
        </li>
        <li class="active">{% trans "Delete?" %}</li>
    </ul>
{% endblock %}

{% block headertext %}
    {{ object.name }}
{% endblock %}

{% block dashboard_content %}
    <form action="." method="post">
        {% csrf_token %}
        <p>{% trans "Are you sure you want to delete this benefit?" %}</p>
        {% if object.offers.count %}
            <p>{% trans "Deleting this benefit will also delete the following offers:" %}</p>
            <ul>
                {% for offer in object.offers.all %}
                    <li><a href="{% url 'dashboard:offer-detail' pk=offer.pk %}">{{ offer.name }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="form-actions">
            <button class="btn btn-lg btn-danger" type="submit" data-loading-text="{% trans 'Deleting...' %}">{% trans "Delete" %}</button> {% trans "or" %}
            <a href="{% url 'dashboard:benefit-list' %}">{% trans "cancel" %}</a>
        </div>
    </form>
{% endblock dashboard_content %}

server/src/oscarbluelight/templates/oscar/dashboard/offers/benefit_edit.html
{% extends 'oscar/dashboard/layout.html' %}

{% load currency_filters %}

{% load i18n %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block title %}
    {% if object.pk %}
        {{ object.name }}:
    {% else %}
        {% trans "Create new benefit" %}:
    {% endif %}
    {{ title }} | {% trans "Benefits" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
    <li>
        <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
    </li>
    <li>
        <a href="{% url 'dashboard:benefit-list' %}">{% trans "Benefits" %}</a>
    </li>
    {% if object.pk %}
        <li>
            <a href="{% url 'dashboard:benefit-update' pk=object.pk %}">{{ object.name }}</a>
        </li>
    {% else %}
        <li>
            {% trans "Create new benefit" %}
        </li>
    {% endif %}
</ul>
{% endblock %}

{% block headertext %}
    {% if not object.pk %}
        {% trans "Create new benefit" %}
    {% else %}
        {{ object.name }}
    {% endif %}
{% endblock %}

{% block dashboard_content %}
    <div class="row">
        <div class="col-md-6">
            <form action="." method="post" class="form-stacked wysiwyg fixed-actions">
                <div class="table-header">
                    <h3>{% trans "Details" %}</h3>
                </div>
                <div class="well">
                    {% csrf_token %}

                    {% if form.is_bound and not form.is_valid %}
                        <div class="alert alert-danger">
                            <strong>{% trans "Oops! We found some errors" %}</strong> - {% trans "please check the error messages below and try again" %}
                        </div>
                    {% endif %}

                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger form-group has-error">
                                <span class="help-inline"><i class="icon-exclamation-sign"></i> {{ error }}</span>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <p>{% trans "Fields marked with * are mandatory." %}</p>

                    {% block form_fields %}
                        {% include "oscar/dashboard/partials/form_field.html" with field=form.range %}
                        <p>
                            {% url 'dashboard:range-list' as range_list_url %}
                            {% blocktrans %}
                            Ranges can be created and edited from within the <a href="{{ range_list_url }}">range dashboard</a>.
                            {% endblocktrans %}
                        </p>

                        {% include "oscar/dashboard/partials/form_field.html" with field=form.proxy_class %}
                        {% include "oscar/dashboard/partials/form_field.html" with field=form.value %}
                        {% include "oscar/dashboard/partials/form_field.html" with field=form.max_affected_items %}
                    {% endblock %}
                </div>

                <div class="fixed-actions-group">
                    <div class="form-actions">
                        <div class="pull-right">
                            <button class="btn btn-default" name="save" type="submit" data-loading-text="{% trans 'Saving...' %}">{% trans "Save" %}</button>
                        </div>
                        <a class="btn btn-default" href="{% url 'dashboard:benefit-list' %}">{% trans "Cancel" %}</a>
                        {% if object.pk %}
                            <a class="btn btn-danger" href="{% url 'dashboard:benefit-delete' pk=object.pk %}">{% trans "Delete" %}</a></li>
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
        {% if object.non_voucher_offers %}
            <div class="col-md-4">
                <div class="table-header">
                    <h3>{% trans "Used by Offers" %}</h3>
                </div>
                <div class="well">
                    <ul>
                        {% for offer in object.non_voucher_offers %}
                            <li><a href="{% url 'dashboard:offer-detail' pk=offer.pk %}">{{ offer.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
        {% if object.vouchers %}
            <div class="col-md-4">
                <div class="table-header">
                    <h3>{% trans "Used by Vouchers" %}</h3>
                </div>
                <div class="well">
                    <ul>
                        {% for voucher in object.vouchers %}
                            <li><a href="{% url 'dashboard:voucher-stats' pk=voucher.pk %}">{{ voucher.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock dashboard_content %}

server/src/oscarbluelight/templates/oscar/dashboard/offers/benefit_edit_compound.html
{% extends 'oscar/dashboard/offers/benefit_edit.html' %}

{% load currency_filters %}
{% load i18n %}

{% block form_fields %}
    {% include "oscar/dashboard/partials/form_field.html" with field=form.subbenefits %}
{% endblock %}

server/src/oscarbluelight/templates/oscar/dashboard/offers/benefit_list.html
{% extends 'oscar/dashboard/layout.html' %}

{% load currency_filters %}
{% load sorting_tags %}
{% load i18n %}

{% block title %}
    {% trans "Benefits" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{{ homepage_url }}">{% trans "Dashboard" %}</a>
        </li>
        <li class="active">{% trans "Benefits" %}</li>
    </ul>
{% endblock %}

{% block header %}
    <div class="page-header">
        <p class="pull-right">
            <a href="{% url 'dashboard:benefit-create' %}" class="btn btn-primary btn-lg">
                <i class="icon-plus"></i> {% trans "Create new benefit" %}
            </a>
            <a href="{% url 'dashboard:benefit-create-compound' %}" class="btn btn-primary btn-lg">
                <i class="icon-plus"></i> {% trans "Create new compound benefit" %}
            </a>
        </p>
        <h1>{% trans "Benefits" %}</h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    <div class="well">
        <form action="." method="get" class="form-inline">
            {% include 'oscar/dashboard/partials/form_fields_inline.html' with form=form %}
            <button type="submit" class="btn btn-primary" data-loading-text="{% trans 'Searching...' %}">{% trans "Search" %}</button>
        </form>
    </div>

    <form action="." method="post" class="order_table">
        {% csrf_token %}
        <table class="table table-striped table-bordered">
            <caption>
                <i class="icon-gift icon-large"></i>{{ queryset_description }}
                {% if is_filtered %}
                    <a href="{% url 'dashboard:benefit-list' %}" >{% trans "Reset" %}</a>
                {% endif %}
            </caption>
            {% if benefits %}
                <tr>
                    <th>{% trans 'Name' %}</th>
                    <th>{% trans 'Range' %}</th>
                    <th>{% trans 'Type' %}</th>
                    <th>{% trans 'Value' %}</th>
                    <th>{% trans 'Used by Offers' %}</th>
                    <th>{% trans 'Used by Vouchers' %}</th>
                    <th>{% trans 'Used by Benefits' %}</th>
                    <th></th>
                </tr>
                {% for benefit in benefits %}
                    <tr>
                        <td><a href="{% url 'dashboard:benefit-update' pk=benefit.pk %}">{{ benefit.name }}</a></td>
                        <td>{{ benefit.range.name|default:"-" }}</td>
                        <td>{{ benefit.type_name|default:"-" }}</td>
                        <td>{{ benefit.value|default:"-" }}</td>
                        <td>
                            <ul>
                                {% for offer in benefit.non_voucher_offers %}
                                    <li><a href="{% url 'dashboard:offer-detail' pk=offer.pk %}">{{ offer.name }}</li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td>
                            <ul>
                                {% for voucher in benefit.vouchers %}
                                    <li><a href="{% url 'dashboard:voucher-stats' pk=voucher.pk %}">{{ voucher.name }}</li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td>
                            <ul>
                                {% for benefit in benefit.parent_benefits.all %}
                                    <li><a href="{% url 'dashboard:benefit-update' pk=benefit.pk %}">{{ benefit.name }}</li>
                                {% endfor %}
                            </ul>
                        </td>
                        <td>
                            <div class="btn-toolbar">
                                <div class="btn-group">
                                    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="true">
                                        {% trans "Actions" %}
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="{% url 'dashboard:benefit-update' pk=benefit.pk %}">{% trans "Edit" %}</a></li>
                                        <li><a href="{% url 'dashboard:benefit-delete' pk=benefit.pk %}">{% trans "Delete" %}</a></li>
                                    </ul>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}

            {% else %}
                <tr><td>{% trans "No benefits found." %}</td></tr>
            {% endif %}
        </table>
        {% include "oscar/dashboard/partials/pagination.html" %}
    </form>
{% endblock dashboard_content %}

server/src/oscarbluelight/templates/oscar/dashboard/offers/benefit_selection_form.html
{% extends 'oscar/dashboard/offers/step_form.html' %}
{% load i18n %}


{% block progress %}
    {% include 'oscar/dashboard/offers/progress.html' with step=2 %}
{% endblock %}


{% block form_fields %}
    <span class="error-block">{{ form.non_field_errors }}</span>

    {% include "oscar/dashboard/partials/form_field.html" with field=form.benefit %}
    <p>
        {% url 'dashboard:benefit-list' as benefit_list_url %}
        {% blocktrans %}
        Incentives can be created and edited from within the <a href="{{ benefit_list_url }}">benefit dashboard</a>.
        {% endblocktrans %}
    </p>
{% endblock %}


{% block submittext %}{% trans "Continue to step 3" %}{% endblock %}


{% block onbodyload %}
    {{ block.super }}
    oscar.dashboard.offers.init();
{% endblock %}

server/src/oscarbluelight/templates/oscar/dashboard/offers/restrictions_form.html
{% extends 'oscar/dashboard/offers/restrictions_form.html' %}

{% block extrascripts %}
    {{ block.super }}

    <script type="text/javascript">
        var groupCheckbox = $('#id_limit_by_group'),
            groupSelect = $('#id_groups');

        groupSelect.prop("disabled", !groupCheckbox.get(0).checked);
        groupCheckbox.on('change', function() {
            groupSelect.prop("disabled", !this.checked);
        });
    </script>
{% endblock %}