server/src/oscarbluelight/dashboard/offers/models.py
from oscar.apps.dashboard.offers.models import *  # noqa

server/src/oscarbluelight/voucher/models.py
from django.db import models, transaction
from django.utils.translation import ugettext_lazy as _
from oscar.apps.voucher.abstract_models import AbstractVoucher
from . import tasks
import time


class VoucherQuerySet(models.QuerySet):
    def exclude_children(self):
        return self.filter(parent=None)

    def select_for_update(self):
        """
        To do a select_for_updarte, we have to reset the query ordering so that it doesn't try to do
        outer joins to the ConditionalOffer and OfferGroup tables.
        """
        qs = self.order_by('pk')
        return models.QuerySet.select_for_update(qs)


class VoucherManager(models.Manager):
    def get_queryset(self):
        return VoucherQuerySet(self.model, using=self._db)

    def exclude_children(self):
        return self.get_queryset().exclude_children()


class Voucher(AbstractVoucher):
    parent = models.ForeignKey('self',
        verbose_name=_("Parent Voucher"),
        related_name='children',
        on_delete=models.CASCADE,
        null=True,
        blank=True)
    limit_usage_by_group = models.BooleanField(_("Limit usage to selected user groups"),
        default=False)
    groups = models.ManyToManyField('auth.Group',
        verbose_name=_("User Groups"),
        blank=True)

    objects = VoucherManager()

    class Meta:
        base_manager_name = 'objects'
        ordering = ('-offers__offer_group__priority', '-offers__priority', 'pk')


    @property
    def offer_group(self):
        offer = self.offers.first()
        return offer.offer_group if offer else None


    @property
    def priority(self):
        offer = self.offers.first()
        return offer.priority if offer else 0


    @property
    def condition(self):
        offer = self.offers.first()
        return offer.condition if offer else None


    @property
    def benefit(self):
        offer = self.offers.first()
        return offer.benefit if offer else None


    def is_available_to_user(self, user=None):
        # Parent vouchers can not be used directly
        if self.children.exists():
            message = _("This voucher is not available")
            return False, message

        # Enforce user group whitelisting
        if self.limit_usage_by_group:
            message = _("This voucher is only available to selected users")
            if not user:
                return False, message
            group_ids = set(g.id for g in self.groups.all())
            member_ids = set(g.id for g in user.groups.all())
            is_member = len(group_ids & member_ids) > 0
            if not is_member:
                return False, message

        return super().is_available_to_user(user)


    @transaction.atomic
    def create_children(self, count):
        if self.parent is not None:
            raise RuntimeError(_('Can not create children for a child voucher. Nesting should only be 1 level.'))
        if not self.id:
            self.save()
        children = []
        for i in range(count):
            code = self._get_child_code(i, count)
            child = self._create_child(i, code)
            children.append(child)
        return children


    @transaction.atomic
    def update_children(self):
        for child in self.children.all():
            self._update_child(child)


    @transaction.atomic
    def save(self, update_children=True, *args, **kwargs):
        rc = super().save(*args, **kwargs)
        if update_children:
            tasks.update_child_vouchers.apply_async(args=(self.id, ), countdown=10)
        return rc


    @transaction.atomic
    def delete(self, *args, **kwargs):
        offers = self.offers.all()
        rc = super().delete(*args, **kwargs)
        for offer in offers:
            # Delete the benefit and offer, since they're auto created
            condition = offer.condition
            offer.delete()
            if condition.offers.count() == 0:
                condition.delete()
        return rc


    def record_usage(self, order, user, *args, **kwargs):
        if self.parent:
            if user.is_authenticated:
                self.parent.applications.create(voucher=self.parent, order=order, user=user)
            else:
                self.parent.applications.create(voucher=self.parent, order=order)
            self.parent.num_orders += 1
            self.parent.save(update_children=False)

        return super().record_usage(order, user, *args, **kwargs)
    record_usage.alters_data = True


    def record_discount(self, discount, *args, **kwargs):
        """ Extends parent class to record discount on the parent Voucher
        Ensures that parent save does not save it's children which would cause
        excessive writes. """
        if self.parent:
            self.parent.total_discount += discount['discount']
            self.parent.save(update_children=False)
        return super().record_discount(discount, *args, **kwargs)
    record_discount.alters_data = True


    def _create_child(self, index, code):
        child = self.__class__()
        child.code = code
        self._update_child(child)
        return child


    def _update_child(self, child):
        child.parent = self
        copy_fields = ('name', 'usage', 'start_datetime', 'end_datetime', 'limit_usage_by_group')
        for field in copy_fields:
            setattr(child, field, getattr(self, field))
        # TODO: Might be useful to use django-dirtyfields here to prevent unnecessary DB writes.
        child.save(update_children=False)
        child.offers.set(list(self.offers.all()))
        child.groups.set(list(self.groups.all()))
        child.save(update_children=False)


    def _get_child_code(self, code_index, max_index, max_tries=50):
        try_count = 0
        while try_count < max_tries:
            try_count += 1
            code = "%s-%s" % (self.code, self._get_code_uniquifier(code_index, max_index))
            try:
                self.__class__.objects.get(code=code)
            except Voucher.DoesNotExist:
                return code
        raise RuntimeError(_("Couldn't find a unique child code after %s iterations.") % try_count)


    def _get_code_uniquifier(self, code_index, max_index, extra_length=3):
        # Make sure all codes are the same length
        index = str(code_index).zfill(len(str(max_index)))
        # Append some digits to the end to make the codes non-sequential
        suffix = str(time.time()).replace('.', '')[-extra_length:]
        return "%s%s" % (index, suffix)


from oscar.apps.voucher.models import *  # noqa

server/src/oscarbluelight/dashboard/vouchers/forms.py
from django import forms
from django.contrib.auth.models import Group
from django.utils.translation import ugettext_lazy as _
from oscar.core.loading import get_model
from oscar.forms import widgets

Voucher = get_model('voucher', 'Voucher')
Benefit = get_model('offer', 'Benefit')
Condition = get_model('offer', 'Condition')
Range = get_model('offer', 'Range')
OfferGroup = get_model('offer', 'OfferGroup')

MAX_CHILDREN_CREATE = 1000


class VoucherForm(forms.Form):
    name = forms.CharField(
        label=_("Name"), max_length=128)
    description = forms.CharField(
        label=_("Description"),
        widget=forms.Textarea,
        required=False)
    code = forms.CharField(
        label=_("Code"))
    create_children = forms.BooleanField(
        label=_('Should child codes be created?'),
        required=False)
    child_count = forms.IntegerField(
        label=_('How many child codes should be created?'),
        initial=0,
        min_value=0,
        max_value=MAX_CHILDREN_CREATE,
        required=False)
    start_datetime = forms.DateTimeField(
        label=_("Start datetime"),
        widget=widgets.DateTimePickerInput())
    end_datetime = forms.DateTimeField(
        label=_("End datetime"),
        widget=widgets.DateTimePickerInput())
    priority = forms.IntegerField(
        label=_("Priority"),
        initial=0, min_value=0,
        help_text=_("The highest priority vouchers are applied first"))
    usage = forms.ChoiceField(
        label=_("Usage"),
        choices=Voucher.USAGE_CHOICES)
    limit_usage_by_group = forms.BooleanField(
        label=_('Should usage be limited to specific user groups?'),
        required=False)
    groups = forms.ModelMultipleChoiceField(
        label=_('User Group Whitelist'),
        help_text=_("Which user groups will be able to apply this offer?"),
        queryset=Group.objects.order_by('name'),
        required=False)
    condition = forms.ModelChoiceField(
        label=_('Condition'),
        help_text=_("In addition to entering the voucher code, what precondition (if any) must be met before this voucher is applied?"),
        queryset=Condition.objects.get_queryset(),
        required=False)
    desktop_image = forms.ImageField(
        label=_('Desktop Image'),
        help_text=_("Desktop image used for promo display."),
        required=False)
    mobile_image = forms.ImageField(
        label=_('Mobile Image'),
        help_text=_("Mobile image used for promo display."),
        required=False)
    benefit = forms.ModelChoiceField(
        label=_('Incentive'),
        help_text=_("What benefit should be given to the customer as a result of this voucher code?"),
        queryset=Benefit.objects.get_queryset())
    offer_group = forms.ModelChoiceField(
        label=_('Offer Group'),
        help_text=_("What group should this voucher belong to?"),
        queryset=OfferGroup.objects.get_queryset())
    max_global_applications = forms.IntegerField(
        label=_("Max global applications"),
        min_value=0, required=False,
        help_text=_("The number of times this offer can be used before it is unavailable"))
    max_user_applications = forms.IntegerField(
        label=_("Max user applications"),
        min_value=0, required=False,
        help_text=_("The number of times a single user can use this offer"))
    max_basket_applications = forms.IntegerField(
        label=_("Max basket applications"),
        min_value=0, required=False,
        help_text=_("The number of times this offer can be applied to a basket (and order)"))
    max_discount = forms.DecimalField(
        label=_("Max discount"),
        min_value=0, decimal_places=2, max_digits=12, required=False,
        help_text=_("When an offer has given more discount to orders than this threshold, then the offer becomes unavailable"))

    def __init__(self, voucher=None, *args, **kwargs):
        self.voucher = voucher
        super().__init__(*args, **kwargs)

    def clean_name(self):
        name = self.cleaned_data['name'].strip()
        if not name:
            raise forms.ValidationError(_("Please enter a voucher name"))
        qs = Voucher.objects
        if self.voucher:
            qs = qs.exclude(pk=self.voucher.pk)
        qs = qs.filter(parent=None)
        qs = qs.filter(name=name)
        if qs.count() > 0:
            raise forms.ValidationError(_("The name '%s' is already in use") % name)
        return name

    def clean_code(self):
        code = self.cleaned_data['code'].strip().upper()
        if not code:
            raise forms.ValidationError(_("Please enter a voucher code"))
        qs = Voucher.objects
        if self.voucher:
            qs = qs.exclude(pk=self.voucher.pk)
        qs = qs.filter(code=code)
        if qs.count() > 0:
            raise forms.ValidationError(_("The code '%s' is already in use") % code)
        return code

    def clean(self):
        cleaned_data = super().clean()
        start_datetime = cleaned_data.get('start_datetime')
        end_datetime = cleaned_data.get('end_datetime')
        if start_datetime and end_datetime and end_datetime < start_datetime:
            raise forms.ValidationError(_("The start date must be before the end date"))
        return cleaned_data


class AddChildCodesForm(forms.Form):
    child_count = forms.IntegerField(
        label=_('How many child codes should be created?'),
        initial=0,
        min_value=0,
        max_value=MAX_CHILDREN_CREATE)

server/src/oscarbluelight/dashboard/offers/__init__.py
default_app_config = 'oscarbluelight.dashboard.offers.apps.OffersDashboardConfig'

server/src/oscarbluelight/dashboard/vouchers/__init__.py
default_app_config = 'oscarbluelight.dashboard.vouchers.apps.VouchersDashboardConfig'

server/src/oscarbluelight/voucher/__init__.py
default_app_config = 'oscarbluelight.voucher.apps.VoucherConfig'

server/src/oscarbluelight/templates/oscar/dashboard/vouchers/voucher_add_children.html
{% extends 'oscar/dashboard/layout.html' %}
{% load currency_filters %}
{% load i18n %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block title %}
    {% trans "Add children" %} | {% trans "Vouchers" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:voucher-list' %}">{% trans "Vouchers" %}</a>
        </li>
        <li>
            <a href="{% url 'dashboard:voucher-stats' pk=voucher.id %}">{{ voucher }}</a>
        </li>
        <li class="active">{% trans "Add children" %}</li>
    </ul>
{% endblock %}

{% block headertext %}{% trans "Add children" %}{% endblock %}

{% block dashboard_content %}
    <div class="table-header">
        <h2><i class="icon-user icon-large"></i>{% trans "Add children" %}</h2>
    </div>
    <form action="." method="post" class="well form-stacked">
        {% csrf_token %}
        {% include "oscar/dashboard/partials/form_fields.html" with form=form %}
        {% block form_actions %}
            <div class="form-actions">
                <button class="btn btn-primary btn-lg" type="submit" data-loading-text="{% trans 'Saving...' %}">{% trans "Save" %}</button> {% trans "or" %}
                <a href="{% url 'dashboard:voucher-list' %}">{% trans "cancel" %}</a>
            </div>
        {% endblock form_actions %}
    </form>
{% endblock dashboard_content %}

server/src/oscarbluelight/templates/oscar/dashboard/vouchers/voucher_detail.html
{% extends 'oscar/dashboard/vouchers/voucher_detail.html' %}
{% load currency_filters %}
{% load sorting_tags %}
{% load i18n %}

{% block header %}
    <div class="page-header">
        <div class="pull-right">
            <a class="btn btn-primary" href="{% url 'dashboard:voucher-update' pk=voucher.id %}">{% trans "Edit" %}</a>
            <a class="btn btn-danger" href="{% url 'dashboard:voucher-delete' pk=voucher.id %}">{% trans "Delete" %}</a>
        </div>
        <h1>{{ voucher }}</h1>
    </div>
{% endblock header %}

{% block dashboard_content %}
    <div class="table-header">
        <h2>{% trans "Voucher details" %}</h2>
    </div>
    <table class="table table-striped table-bordered table-hover">
        <tbody>
            <tr>
                <th>{% trans "Name" %}</th>
                <td>{{ voucher.name }}</td>
                <td></td>
            </tr>
            <tr>
                <th>{% trans "Description" %}</th>
                <td>{{ voucher.offers.first.description|safe }}</td>
                <td></td>
            </tr>
            <tr>
                <th>{% trans "Code" %}</th>
                <td>{{ voucher.code }}</td>
                <td></td>
            </tr>
            <tr>
                <th>{% trans "Num child codes" %}</th>
                <td>{{ children.count }}</td>
                <td>
                    <div class="btn-toolbar">
                        <div class="btn-group">
                            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="true">
                                {% trans "Actions" %}
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="{% url 'dashboard:voucher-add-children' pk=voucher.id %}">{% trans "Add more child codes" %}</a></li>
                                <li><a href="{% url 'dashboard:voucher-export-children' pk=voucher.id format='csv' %}">{% trans "Export codes as CSV" %}</a></li>
                                <li><a href="{% url 'dashboard:voucher-export-children' pk=voucher.id format='json' %}">{% trans "Export codes as JSON" %}</a></li>
                            </ul>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <th>{% trans "Priority" %}</th>
                <td>{{ voucher.priority }}</td>
                <td></td>
            </tr>
            <tr>
                <th>{% trans "Start datetime" %}</th>
                <td>{{ voucher.start_datetime }}</td>
                <td></td>
            </tr>
            <tr>
                <th>{% trans "End datetime" %}</th>
                <td>{{ voucher.end_datetime }}</td>
                <td></td>
            </tr>
            <tr>
                <th>{% trans "Desktop Image" %}</th>
                <td>
                    {% if voucher.offers.first %}
                        {% include "oscar/dashboard/vouchers/voucher_thumbnail.html" with record=voucher.offers.first.desktop_image %}
                    {% endif %}
                </td>
                <td></td>
            </tr>
            <tr>
                <th>{% trans "Mobile Image" %}</th>
                <td>
                    {% if voucher.offers.first %}
                        {% include "oscar/dashboard/vouchers/voucher_thumbnail.html" with record=voucher.offers.first.mobile_image %}
                    {% endif %}
                </td>
                <td></td>
            </tr>
            <tr>
                <th>{% trans "Usage" %}</th>
                <td>{{ voucher.get_usage_display }}</td>
                <td></td>
            </tr>
            <tr>
                <th>{% trans "Condition" %}</th>
                <td>{{ voucher.condition.description|safe }}</td>
                <td></td>
            </tr>
            <tr>
                <th>{% trans "Discount" %}</th>
                <td>{{ voucher.benefit.description|safe }}</td>
                <td></td>
            </tr>
            <tr>
                <th>{% trans "Usage is limited to specific user groups?" %}</th>
                <td>
                    {% if voucher.limit_usage_by_group %}
                        <span class="label label-success">{% trans "Yes" %}</span>
                    {% else %}
                        <span class="label label-danger">{% trans "No" %}</span>
                    {% endif %}
                </td>
                <td></td>
            </tr>
            {% if voucher.limit_usage_by_group %}
                <tr>
                    <th>{% trans "Whitelisted User Groups" %}</th>
                    <td>
                        {% for group in voucher.groups.all %}
                            <span class="label label-info">{{ group.name }}</span>
                        {% endfor %}
                    </td>
                    <td></td>
                </tr>
            {% endif %}
            <tr>
                <th>{% trans "Offer Group" %}</th>
                    <td>{{ voucher.offer_group.name|default:"-" }}</td>
                <td></td>
            </tr>
        </tbody>
    </table>


    <div class="table-header">
        <h2>{% trans "Voucher performance" %}</h2>
    </div>
    <table class="table table-striped table-bordered table-hover">
        <tbody>
            <tr><th>{% trans "Number of basket additions" %}</th><td>{{ voucher.num_basket_additions }}</td></tr>
            <tr><th>{% trans "Number of orders" %}</th><td>{{ voucher.num_orders }}</td></tr>
            <tr><th>{% trans "Total discount" %}</th><td>{{ voucher.total_discount|currency }}</td></tr>
        </tbody>
    </table>


    <h2>{% trans "Orders that used this voucher" %}</h2>
    <div class="well">
        <form method="get" class="form">
            {% include 'oscar/dashboard/partials/form_fields.html' with form=form %}
            <button type="submit" class="btn btn-primary" data-loading-text="{% trans 'Searching...' %}">
                {% trans "Search" %}
            </button>
            <button
                type="submit"
                class="btn btn-default"
                name="format"
                value="csv"
            >
                {% trans "Export to CSV" %}
            </button>
            {% if is_filtered %}
                <a class="btn btn-default" href="{% url 'dashboard:voucher-stats' pk=voucher.id %}">
                    {% trans "Reset" %}
                </a>
            {% endif %}
        </form>
    </div>
    <div class="table-header">
        {% if is_filtered %}
            <h2>{% trans "Orders matching search" %}</h2>
        {% else %}
            <h2>{% trans "All orders" %}</h2>
        {% endif %}
    </div>
    <table class="table table-striped table-bordered table-hover">
        {% if not discounts %}
            <tr>
                <td><em>{% trans "No orders have been placed that use this voucher." %}</em></td>
            </tr>
        {% else %}
            <thead>
                <tr>
                    <th>{% trans "Order number" %}</th>
                    <th>{% trans "Order status" %}</th>
                    <th>{% trans "Voucher code" %}</th>
                    <th>{% trans "Order total" %}</th>
                    <th>{% trans "Discount" %}</th>
                    <th>{% trans "Date placed" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for discount in discounts %}
                    {% with order=discount.order %}
                        <tr>
                            <td><a href="{% url 'dashboard:order-detail' number=order.number %}">{{ order.number }}</a></td>
                            <td>{{ order.status }}</td>
                            <td>{{ discount.voucher_code }}</td>
                            <td>{{ order.total_incl_tax|currency:order.currency }}</td>
                            <td>{{ discount.amount|currency:order.currency }}</td>
                            <td>{{ order.date_placed }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
        {% endif %}
    </table>
    {% include 'oscar/dashboard/partials/pagination.html' %}
{% endblock %}

server/src/oscarbluelight/templates/oscar/dashboard/vouchers/voucher_form.html
{% extends 'oscar/dashboard/vouchers/voucher_form.html' %}
{% load currency_filters %}
{% load i18n %}

{% block dashboard_content %}
    <form action="." method="post" enctype="multipart/form-data" class="form-stacked wysiwyg fixed-actions">
        {% csrf_token %}

        <div class="row">
            <div class="col-md-6">
                <div class="table-header">
                    <h2><i class="icon-money icon-large"></i>
                        {% if voucher %}
                            {% trans "Edit voucher" %}
                        {% else %}
                            {% trans "Create voucher" %}
                        {% endif %}
                    </h2>
                </div>
                <div class="well">
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.name %}
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.description %}

                    {% include "oscar/dashboard/partials/form_field.html" with field=form.code %}

                    {% include "oscar/dashboard/partials/form_field.html" with field=form.priority %}

                    {% include "oscar/dashboard/partials/form_field.html" with field=form.start_datetime %}
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.end_datetime %}
                </div>

                <div class="table-header">
                    <h2><i class="icon-money icon-large"></i>
                        {% trans "Coupon Display" %}
                    </h2>
                </div>
                <div class="well">
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.desktop_image %}
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.mobile_image %}
                </div>

                <div class="table-header">
                    <h2><i class="icon-gift icon-large"></i>
                        {% trans "Condition" %}
                    </h2>
                </div>
                <div class="well">
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.condition %}
                    <p>
                        {% url 'dashboard:condition-list' as condition_list_url %}
                        {% blocktrans %}
                        Conditions can be created and edited from within the <a href="{{ condition_list_url }}">condition dashboard</a>.
                        {% endblocktrans %}
                    </p>
                </div>

                <div class="table-header">
                    <h2><i class="icon-gift icon-large"></i>
                        {% trans "Reward" %}
                    </h2>
                </div>
                <div class="well">
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.benefit %}
                    <p>
                        {% url 'dashboard:benefit-list' as benefit_list_url %}
                        {% blocktrans %}
                        Incentives can be created and edited from within the <a href="{{ benefit_list_url }}">benefit dashboard</a>.
                        {% endblocktrans %}
                    </p>
                </div>
                <div class="table-header">
                    <h2><i class="icon-gift icon-large"></i>
                        {% trans "Offer Group" %}
                    </h2>
                </div>
                <div class="well">
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.offer_group %}
                    <p>
                        {% url 'dashboard:offergroup-list' as offergroup_list_url %}
                        {% blocktrans %}
                        Offer groups can be created and edited from within the <a href="{{ offergroup_list_url }}">offer group dashboard</a>.
                        {% endblocktrans %}
                    </p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="table-header">
                    <h2><i class="icon-cogs icon-large"></i>
                        {% trans "Child Codes" %}
                    </h2>
                </div>
                <div class="well">
                    {% if voucher %}
                        {% if voucher.children.count %}
                            <p>{% blocktrans with voucher.children.count as count %}All changes will apply to this voucher and its {{ count }} child codes.{% endblocktrans %}</p>
                        {% else %}
                            <p>{% blocktrans %}This voucher has no children.{% endblocktrans %}</p>
                        {% endif %}
                    {% else %}
                        {% include "oscar/dashboard/partials/form_field.html" with field=form.create_children %}
                        {% include "oscar/dashboard/partials/form_field.html" with field=form.child_count %}
                    {% endif %}
                </div>

                <div class="table-header">
                    <h2><i class="icon-user icon-large"></i>
                        {% trans "Usage Constraints" %}
                    </h2>
                </div>
                <div class="well">
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.usage %}
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.limit_usage_by_group %}
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.groups %}
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.max_global_applications %}
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.max_user_applications %}
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.max_basket_applications %}
                    {% include "oscar/dashboard/partials/form_field.html" with field=form.max_discount %}
                </div>
            </div>
        </div>

        {% block form_actions %}
            <div class="fixed-actions-group">
                <div class="form-actions">
                    <div class="pull-right">
                        <button class="btn btn-primary btn-lg" type="submit" data-loading-text="{% trans 'Saving...' %}">{% trans "Save" %}</button> {% trans "or" %}
                    </div>

                    <a class="btn btn-default btn-lg" href="{% url 'dashboard:voucher-list' %}">{% trans "Cancel" %}</a>
                </div>
            </div>
        {% endblock form_actions %}
    </form>
{% endblock dashboard_content %}


{% block extrascripts %}
    {{ block.super }}

    <script type="text/javascript">
        var groupCheckbox = $('#id_limit_usage_by_group'),
            groupSelect = $('#id_groups'),
            childrenCheckbox = $('#id_create_children'),
            childrenCount = $('#id_child_count');

        if (groupCheckbox.length > 0 && groupSelect.length > 0) {
            groupSelect.prop("disabled", !groupCheckbox.get(0).checked);
            groupCheckbox.on('change', function() {
                groupSelect.prop("disabled", !this.checked);
            });
        }

        if (childrenCheckbox.length > 0 && childrenCount.length > 0) {
            childrenCount.prop("disabled", !childrenCheckbox.get(0).checked);
            childrenCheckbox.on('change', function() {
                childrenCount.prop("disabled", !this.checked);
            });
        }
    </script>
{% endblock %}

server/src/oscarbluelight/templates/oscar/dashboard/vouchers/voucher_thumbnail.html
{% load thumbnail %}
{% if record %}
    {% with image=record %}
        {% thumbnail image "70x70" upscale=False as thumb %}
            <img src="{{ thumb.url }}" alt="{{ image.url }}" height="{{ thumb.height }}" width="{{ thumb.width }}">
        {% endthumbnail %}
    {% endwith %}
{% else %}
    —
{% endif %}